### ISSUE TITLE
implement greek stemmer in lunr.js

### ISSUE THREAD

**Issue by miljkovicmisa** [Apmats/greekstemmerjs#1]
Is it possible to implement this js stemmer into the [lunr.js](lunrjs.com) full-text search engine for greek language support?

**Comment by Apmats** [comment]
I haven't had experience with lunr.js before, but after having a look you can probably override the stemmer used with something like this:

``` javascript
var lunr = require('lunr'),
    greekStemmer = require('greek-stemmer');


lunr.trimmer = function trim(word) { return word };
lunr.stemmer = greekStemmer.stem;

lunr.Pipeline.registerFunction(lunr.stemmer, 'stemmer');
lunr.Pipeline.registerFunction(lunr.trimmer, 'trimmer');

var idx = lunr(function () {
  this.ref('id')

  this.field('title', { boost: 10 })
  this.field('author', { boost: 100 })
  this.field('body')
})




var doc = {
    "title": "ΕΝΑΣ ΤΙΤΛΟΣ ΕΔΩ",
    "body": "ΚΑΠΟΙΟΣ",
    "author": "ΕΝΑΣ ΣΥΓΓΡΑΦΕΑΣ",
    "id": 1
}
idx.add(doc);

console.log(idx.search("ΚΑΠΟΙOI"));
```

You also need to override the trimmer as far as I can see, because otherwise all non-latin characters in words are discarded, maybe you will need to make your own that makes sense for greek.
